server:
  port: 8080

spring:
  application:
    name: PasteBook
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

s3:
  url: ${S3_ENDPOINT}
  accessKey: ${S3_ACCESS_KEY_ID}
  secretKey: ${S3_SECRET_ACCESS_KEY}
  bucket: ${S3_BUCKET}